name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, dom
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Update Composer dependencies
      run: composer update --prefer-dist --no-progress

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit
      run: vendor/bin/phpunit --configuration phpunit.xml